import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script src="/dist/jeelizFaceFilter.js" />
        <Script src="/libs/three/v112/three.min.js" />
        <Script src="/helpers/JeelizResizer.js" />
        <Script src="/helpers/JeelizThreeHelper.js" />
        <Script src="/helpers/addDragEventListener.js" />
        <Script type="module" src="/libs/main.js" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
